import { initLogLevel } from "./logger"
import { currentView } from "./state";
import { hidePrivacyPopup, initPrivacy } from "./modules/privacy";
import { initNoticeUrl } from "./modules/notice-url";
import { initWeather } from "./modules/weather";
import { showOnlyView, syncCurrentView } from "./modules/view-switcher";
import { initLyricRenderer } from "./modules/lyric-renderer";
import { initMusicControls } from "./modules/music-controls";
import { initDragger } from "./modules/drag";
import { initCapsuleInteraction } from "./modules/capsule-interaction";
import { initAgent } from "./modules/agent";
import { initResizeObserver } from "./modules/resize-observer";
import { initSearch } from "./modules/search";
import { initSadb } from "./modules/sadb";
import { initEmailResize } from "./modules/email-resize";
import { initEmailView } from "./modules/email-view";
import { initNoticeQueue } from "./modules/notice-queue";
import { initrAF } from "./modules/rAF";
import { initTodo, initCalendar, initClock } from "./modules/panel";
import { initDownloader } from "./modules/downloader";
import { initAgentHandler } from "./modules/agent_handler/handler";
initDownloader();
initLogLevel()
initNoticeUrl();
initNoticeQueue();
initWeather();
initPrivacy();
initLyricRenderer();
initMusicControls();
initDragger();
initCapsuleInteraction();
initAgent();
initSearch();
initSadb();
initEmailView();
initEmailResize();
initResizeObserver();
initrAF();
initTodo();
initClock();
initCalendar();
showOnlyView("time");
hidePrivacyPopup();
initAgentHandler();
void syncCurrentView(currentView);

